## Week 3 part 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')

In [3]:
df=df[0]

In [4]:
df

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

In [5]:
df=df[df['Borough']!='Not assigned']
df

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [6]:
df.describe()

       Postal Code     Borough Neighbourhood
count          103         103           103
unique         103          10            99
top            M1G  North York     Downsview
freq             1          24             4

In [7]:
df['Neighbourhood'].unique()

array(['Parkwoods', 'Victoria Village', 'Regent Park, Harbourfront',
       'Lawrence Manor, Lawrence Heights',
       "Queen's Park, Ontario Provincial Government",
       'Islington Avenue, Humber Valley Village', 'Malvern, Rouge',
       'Don Mills', 'Parkview Hill, Woodbine Gardens',
       'Garden District, Ryerson', 'Glencairn',
       'West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale',
       'Rouge Hill, Port Union, Highland Creek', 'Woodbine Heights',
       'St. James Town', 'Humewood-Cedarvale',
       'Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood',
       'Guildwood, Morningside, West Hill', 'The Beaches', 'Berczy Park',
       'Caledonia-Fairbanks', 'Woburn', 'Leaside', 'Central Bay Street',
       'Christie', 'Cedarbrae', 'Hillcrest Village',
       'Bathurst Manor, Wilson Heights, Downsview North',
       'Thorncliffe Park', 'Richmond, Adelaide, King',
       'Dufferin, Dovercourt Village', 'Scarborough Village',
       'Fairview, Henry Farm, Oriole', 'Northwood Park, York University',
       'East Toronto, Broadview North (Old East York)',
       'Harbourfront East, Union Station, Toronto Islands',
       'Little Portugal, Trinity',
       'Kennedy Park, Ionview, East Birchmount Park', 'Bayview Village',
       'Downsview', 'The Danforth West, Riverdale',
       'Toronto Dominion Centre, Design Exchange',
       'Brockton, Parkdale Village, Exhibition Place',
       'Golden Mile, Clairlea, Oakridge', 'York Mills, Silver Hills',
       'India Bazaar, The Beaches West', 'Commerce Court, Victoria Hotel',
       'North Park, Maple Leaf Park, Upwood Park', 'Humber Summit',
       'Cliffside, Cliffcrest, Scarborough Village West',
       'Willowdale, Newtonbrook', 'Studio District',
       'Bedford Park, Lawrence Manor East',
       'Del Ray, Mount Dennis, Keelsdale and Silverthorn',
       'Humberlea, Emery', 'Birch Cliff, Cliffside West',
       'Willowdale, Willowdale East', 'Lawrence Park', 'Roselawn',
       'Runnymede, The Junction North', 'Weston',
       'Dorset Park, Wexford Heights, Scarborough Town Centre',
       'York Mills West', 'Davisville North',
       'Forest Hill North & West, Forest Hill Road Park',
       'High Park, The Junction South', 'Westmount', 'Wexford, Maryvale',
       'Willowdale, Willowdale West', 'North Toronto West, Lawrence Park',
       'The Annex, North Midtown, Yorkville', 'Parkdale, Roncesvalles',
       'Canada Post Gateway Processing Centre',
       'Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens',
       'Agincourt', 'Davisville', 'University of Toronto, Harbord',
       'Runnymede, Swansea', "Clarks Corners, Tam O'Shanter, Sullivan",
       'Moore Park, Summerhill East',
       'Kensington Market, Chinatown, Grange Park',
       "Milliken, Agincourt North, Steeles East, L'Amoreaux East",
       'Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park',
       'CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport',
       'New Toronto, Mimico South, Humber Bay Shores',
       'South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens',
       "Steeles West, L'Amoreaux West", 'Rosedale', 'Stn A PO Boxes',
       'Alderwood, Long Branch', 'Northwest, West Humber - Clairville',
       'Upper Rouge', 'St. James Town, Cabbagetown',
       'First Canadian Place, Underground city',
       'The Kingsway, Montgomery Road, Old Mill North',
       'Church and Wellesley',
       'Business reply mail Processing Centre, South Central Letter Processing Plant Toronto',
       "Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East",
       'Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West'],
      dtype=object)

In [8]:
df[df['Neighbourhood']=='Not assigned']

Empty DataFrame
Columns: [Postal Code, Borough, Neighbourhood]
Index: []

In [9]:
df.shape

(103, 3)